Compilation test
galasa-dev/integratedtests pull request #170
Opened 2023-01-18 14:55 UTC by AaronJhaj

2023-01-18 15:00 UTC, galasa-team commented
Build successful

2023-01-18 15:45 UTC, hobbit1983 approved these changes

2023-03-09 12:43 UTC, galasa-team commented
Build successful

2023-03-09 13:05 UTC, jadecarino requested changes

2023-03-09 13:05 UTC, jadecarino commented on galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/simbank/AbstractCompilationLocalSimBank.java
> +        makeGradleProperties();
I think what this test is doing, is taking files that already exist in the Simplatform repository on Github and putting them in a new file structure for a test to use. As the gradle.properties file you are trying to create does not exist in Github, you will have to create it then allow it to be copied over like the other folders are.

- Remove this method and call a method on like 54 called 'createParentGradleProperties(simplatformParent)' and implement this method doing a similar thing to what createParentSettings does, but for your gradle.properties file.

2023-03-09 13:05 UTC, jadecarino commented on galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/simbank/AbstractCompilationLocalSimBank.java
> +        Path gradlePropertiesFile = testRunDirectory.resolve("/.gradle/" + gradleProperties);
Move this same logic into a different method called createParentGradleProperties as mentioned in my last comment.

2026-04-28 15:26 UTC, closed without merging