updating maven plugin version
galasa-dev/integratedtests pull request #192
Opened 2024-02-26 11:57 UTC by Akyiaa

Signed-off-by: Fiona Ampofo <64271621+Akyiaa@users.noreply.github.com>

2024-02-26 12:00 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-integratedtests-pr-192-tttwt for details. If you are unable to do so, please contact a member of the Galasa team.

2024-03-05 15:28 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-integratedtests-pr-192-jgshw for details. If you are unable to do so, please contact a member of the Galasa team.

2024-03-05 15:34 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-integratedtests-pr-192-96ddw for details. If you are unable to do so, please contact a member of the Galasa team.

2024-03-05 16:16 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-integratedtests-pr-192-5vktl for details. If you are unable to do so, please contact a member of the Galasa team.

2024-03-06 11:44 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-integratedtests-pr-192-ndxk5 for details. If you are unable to do so, please contact a member of the Galasa team.

2024-03-13 10:09 UTC, galasa-team commented
Build successful

2024-03-13 10:11 UTC, galasa-team commented
Build successful

2024-03-13 10:33 UTC, jadecarino requested changes

2024-03-13 10:33 UTC, jadecarino commented on build-locally.sh
> +    -PtargetMaven=/workspace/git/${context}/inttests/repo \
We can remove the targetMaven line here as that's only required for the remote builds :)

2024-03-13 10:35 UTC, jadecarino approved these changes

2024-03-13 10:40 UTC, galasa-team commented
Build successful

2024-03-13 10:41 UTC, merged